name: Auto Update Rust Skinport HTML

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run scraper script
      run: python skinport_rust_all_scraper.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add rust_skinport_all.html
        git commit -m "Auto update Rust skin data"
        git push
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add rust_skin_data.html || true
        git commit -m "Auto update skin data" || echo "No changes to commit"
        git push
